<%@ page contentType="text/xsl; charset=UTF-8" session="false" %><?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
				xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output metdod="html" version="1.0" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<html>
			<head>
				<title>Sitemap for ${initializationData.applicationName}</title>
				<style type="text/css">
					body {
						font-family: Helvetica, Arial, sans-serif;
						font-size: 13px;
						color: #333;
						margin: 10px;
					}
					a, a:visited {
						color: #333;
						text-decoration: none;
					}
					a:hover {
						text-decoration: underline;
					}
					.message {
						margin: 18px 3px;
						line-height: 1.2em;
					}
					.message a {
						color: #2F63A3;
						font-weight: bold;
					}
					.dataTable {
						margin: 0px;
						padding:0px;
						display: inline-block;
						border: 1px solid #d1d1d1;
						border-bottom: none;
					}
					
					.dataTable table {
					    border-collapse: collapse;
					    border-spacing: 0px;
						margin: 0px;
						padding: 0px;
					}
					.dataTable tr {
					    border-bottom: 1px solid #d1d1d1;
					}
					
					.dataTable tr:ntd-child(odd) {
						background-color: #F9FBFC; 
					}
					
					.dataTable tr:ntd-child(even) {
						background-color: #ffffff;
					}
					
					.dataTable tr:hover {
					    background-color: #fefee2;
					}
					
					.dataTable td {
						vertical-align:middle;
						font-size: 13px;
						font-family: Arial;
						font-weight: normal;
						color: #333333;
					    line-height: 18px;
					    padding: 7px 7px 6px 8px;
					}
					
					.dataTable tr:first-child td {
						background-color: #edf6fc;
						font-family: Arial;
						font-weight: bold;
						color: #333333;
					}

                    img.icon {
                        max-width: 160px;
                        max-height: 80px;
                    }
				</style>
			</head>
			<body>
				<div id="content">
					<h1>Sitemap for ${initializationData.applicationName}</h1>
					<p class="message">Generated by Cyclos version ${cyclosVersion}</p>
					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
						<div class="dataTable">
							<table>
								<tr>
									<td>Sitemap</td>
									<td>Last Modified</td>
								</tr>
								<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
									<xsl:variable name="sitemapURL">
										<xsl:value-of select="sitemap:loc"/>
									</xsl:variable>
									<tr>
										<td>
											<a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
										</td>
										<td>
											<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
										</td>
									</tr>
								</xsl:for-each>
							</table>
						</div>
					</xsl:if>
					<xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
						<p class="message"><a href="${indexUrl}">Go to sitemap index</a></p>
						<div class="dataTable">
							<table>
								<tr>
                                    <td>Image</td>
									<td>URL</td>
									<td>Priority</td>
									<td>Last modified at</td>
								</tr>
								<xsl:for-each select="sitemap:urlset/sitemap:url">
									<tr>
                                        <td>
                                            <xsl:if test="count(image:image) &gt; 0">
                                                <xsl:variable name="imageURL">
                                                    <xsl:value-of select="image:image"/>
                                                </xsl:variable>
                                                <img class="icon" src="{$imageURL}" />
                                            </xsl:if>
                                        </td>
										<td>
											<xsl:variable name="itemURL">
												<xsl:value-of select="sitemap:loc"/>
											</xsl:variable>
											<a href="{$itemURL}">
												<xsl:value-of select="sitemap:loc"/>
											</a>
										</td>
										<td>
											<xsl:value-of select="concat(sitemap:priority*100,'%')"/>
										</td>
										<td>
											<xsl:value-of select="concat(substring(sitemap:lastmod,0,11),concat(' ', substring(sitemap:lastmod,12,5)))"/>
										</td>
									</tr>
								</xsl:for-each>
							</table>
						</div>
					</xsl:if>
				</div>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>